# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-app
service: vision

provider:
  name: aws
  runtime: python3.12
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:DetectFaces
        - rekognition:DetectLabels
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::*"
    - Effect: Allow
      Action:
        - bedrock:InvokeModel
      Resource: "*"

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  visionV1:
    handler: controllers.VisionV1Controller.vision_v1
    events:
      - httpApi:
          path: /v1/vision
          method: post
  visionV2:
    handler: controllers.VisionV2Controller.vision_v2
    events:
      - httpApi:
          path: /v2/vision
          method: post
    timeout: 120
